# Generated by Django 5.2 on 2025-05-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('previous_cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
